-- PR = Player Rating
-- LK = LastKill
-- KC = KillsCount
-- KB = KilledBy
-- PRL = Player Rating Lost
-- PRG = Player Rating Gain
CREATE TABLE IF NOT EXISTS players (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(10) NOT NULL UNIQUE,
    level NUMBER NOT NULL DEFAULT 0,
    guild VARCHAR(10) DEFAULT NULL,
    -- PVP --
    lk TEXT NOT NULL DEFAULT '',
    kc NUMERIC DEFAULT 0,
    -- RANKED --
    inMD3 BOOLEAN DEFAULT 0,
    inMD5 BOOLEAN DEFAULT 0,
    elo TEXT DEFAULT NULL,
    division NUMBER DEFAULT 0,
    pr NUMBER NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) 

CREATE TABLE IF NOT EXISTS bestof (
    id INTEGER PRIMARY KEY NOT NULL,
    name VARCHAR(10) NOT NULL UNIQUE,
    wins NUMBER DEFAULT 0,
    loses NUMBER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (name) REFERENCES characters(name) ON UPDATE CASCADE ON DELETE RESTRICT
) 

CREATE TABLE IF NOT EXISTS kills (
    id INTEGER PRIMARY KEY NOT NULL,
    killed VARCHAR(10) NOT NULL,
    prg NUMBER NOT NULL,
    created_at TEXT DEFAULT (CURRENT_TIMESTAMP),
    FOREIGN KEY (killed) REFERENCES characters(name) ON UPDATE CASCADE ON DELETE RESTRICT
) 

CREATE TABLE IF NOT EXISTS deaths (
    id INTEGER PRIMARY KEY NOT NULL,
    kb VARCHAR(10) NOT NULL,
    prl NUMBER NOT NULL,
    created_at TEXT DEFAULT (CURRENT_TIMESTAMP),
    FOREIGN KEY (kb) REFERENCES characters(name) ON UPDATE CASCADE ON DELETE RESTRICT
)